### ISSUE TITLE
uberscript can output namspaces in the wrong order

### ISSUE THREAD

**Issue by hugoduncan** [borkdude/babashka#535]
```
$ bb --version
babashka v0.1.3
$ defaults read loginwindow SystemVersionStampAsString
10.15.6
```

uberscript outputs namespaces in reverse load order, which is not the same as reverse dependency order.

**repro**

```clojure
(ns my.main
  (:require [my.impl :as impl])
  (:require [my.impl2 :as impl2]))

(defn -main [& args]
  (impl/impl-fn args))
```
```clojure
(ns my.impl)

(defn impl-fn
  "identity"
  [x] x)
```
```clojure
(ns my.impl2
  (:require [my.impl :as impl]))

(def impl-fn impl/impl-fn)
```
```
bb -cp src -m my.main --uberscript
```

`my.impl` should appear in the generated uberscript before `my.impl2`

**Comment by borkdude** [comment]
To fix this, we can figure out namespace dependencies using some library like https://github.com/stuartsierra/dependency.

On the other hand, maybe it's time to just deprecate the uberjar, since `(io/resource ..)` etc also doesn't work and it might cause more confusion that it's worth. 

An alternative would be to create a regular uberjar:

```
borkdude@MBP2019 /tmp/proj $ cat src/proj.clj
(ns proj
  (:require [spartan.spec :as s]))

(defn -main [& _]
  (s/explain int? :foo))
borkdude@MBP2019 /tmp/proj $ cat deps.edn
{:deps {borkdude/spartan.spec {:git/url "https://github.com/borkdude/spartan.spec" :sha "ff7317d67ec15f188afb856d37090e5c9509374e"}}
 :aliases {:depstar
           {:extra-deps
            {seancorfield/depstar {:mvn/version "1.0.97"}}}}}
borkdude@MBP2019 /tmp/proj $ clojure -A:depstar -m hf.depstar.uberjar MyProject.jar
Building uber jar: MyProject.jar
borkdude@MBP2019 /tmp/proj $ bb -cp MyProject.jar -m proj
:foo - failed: int?
```

Maybe we can build an option to let bb directly execute uberjars if the user includes some metadata of where to find the main method. Thoughts?

**Comment by borkdude** [comment]
Ah, if you create a pom with `clojure -Spom` and then run:

```
$ clojure -A:depstar -m hf.depstar.uberjar MyProject.jar  -m proj
Building uber jar: MyProject.jar
Processing pom.xml for {proj/proj {:mvn/version "0.1.0"}}
```

Then the uberjar will contain:

```
$ cat META-INF/MANIFEST.MF
Manifest-Version: 1.0
Built-By: depstar
Build-Jdk: 11.0.3
Main-Class: proj
```

which we can then read with babashka, to pick up on the right main namespace.

**Comment by borkdude** [comment]
We could also fork depstar and include it in babashka to build uberjars. I suspect the code will be compilable with GraalVM.

**Comment by borkdude** [comment]
@hugoduncan I think I fixed it with https://github.com/borkdude/babashka/commit/0829ccbe2ef458ad7408b86bdaf6b934b6cd4384.

Solution: force reload of already loaded namespaces and dedupe sources when writing to script.

**Comment by borkdude** [comment]
@hugoduncan I think the above commit fixed the remaining issue. Also converted your example into a unit test.

**Comment by hugoduncan** [comment]
Nice to see a simple solution. Uberscript seems like a good option for simple scripts, especially with shebang support.

Would `distinct` not be more correct than `dedupe`?

This doesn't seem to solve the issue I was facing that motivated this issue.  I'm not sure why, and will continue to investigate.

**Comment by borkdude** [comment]
@hugoduncan You're right. `distinct` is more efficient, although it already works with `dedupe`.

**Comment by hugoduncan** [comment]
`dedupe` only removes consecutive duplicates - I can't see how that is sufficient.

**Comment by borkdude** [comment]
It is sufficient, but not efficient. With dedupe some namespaces will be reloaded multiple times, but the order is still correct because of how uberscript is implemented. It's been changed now on master.

**Comment by borkdude** [comment]
More details:

Uberscript was originally implemented as follows: each time a namespace is loaded (for the first time) we cons that namespace source to a list. So the last loaded namespace will be a the top of the uberscript. You pointed out that this is sometimes (probably often) not correct.

The patch was then to cons the namespace every time it's required, even when it was already loaded. But some namespace can now occur multiple times in the list. This isn't a problem when evaluating those sources in the order of the list, but removing duplicates is preferable for efficiency and a smaller uberscript.

**Comment by hugoduncan** [comment]
Isn't having the source emitted multiple times a correctness issue?

For example, if namespace `A` has a top level var with some state, maybe in an atom, and namespace `B` has a top level form that causes a change in `A`'s state, then concatenating the source for `A`, `B`, `A` will cause `A`'s state to be reset, iiuc.

**Comment by borkdude** [comment]
@hugoduncan You're right. So `distinct` would fix that issue. Thanks for pointing that out.

**Comment by borkdude** [comment]
Remaining bug here: can't resolve `aero/read-config`.

> Run deps.exe -m makejack.main uberscript in https://github.com/hugoduncan/makejack/tree/wip

Can take a look later this week.

**Comment by borkdude** [comment]
Fixed on master.
